version: '3'

services:
  provider:
    image: dtr.rogfk.no/fint-beta/provider:PR-9
    ports:
      - "8470:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/elev/provider
      fint.events.orgIds: "fint.health,pwf.no"
      fint.events.component: pwf
      fint.events.env: pwf
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-pwf
      fint.provider.sse-timeout-minutes: 19
      fint.hazelcast.members: consumer,provider
      endpoints.trace.sensitive: "false"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  consumer:
    image: dtr.rogfk.no/fint-beta/consumer-utdanning-elev:PR-1
    ports:
      - "8471:8080"
    environment:
      TZ: Europe/Oslo
      server.context-path: /utdanning/elev
      fint.events.orgIds: "fint.health,pwf.no"
      fint.events.component: pwf
      fint.events.env: pwf
      fint.relations.default-base-url: "https://play-with-fint.felleskomponent.no"
      fint.audit.mongo.hostname: 152.93.213.138
      fint.audit.mongo.databasename: fint-audit-pwf
      fint.hazelcast.members: consumer,provider
      fint.cache.manager: hazelcast
      fint.consumer.default-org-id: "pwf.no"
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  health-adapter:
    image: dtr.rogfk.no/fint-beta/health-adapter:1.1.0
    environment:
      TZ: Europe/Oslo
      springfox.title: "Health Adapter"
      fint.adapter.organizations: fint.health
      fint.adapter.sse-endpoint: http://provider:8080/utdanning/elev/provider/sse/%s
      fint.adapter.status-endpoint: http://provider:8080/utdanning/elev/provider/status
      fint.adapter.response-endpoint: http://provider:8080/utdanning/elev/provider/response
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
