apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack-beta.yml
    kompose.version: 1.16.0 (HEAD)
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.stack: utdanning-elev
    fint.role: provider
  name: provider-utdanning-elev
spec:
  ports:
  - name: "8080"
    port: 8080
  type: LoadBalancer
  selector:
    fint.stack: utdanning-elev
    fint.role: provider
