fint:
  events:
    orgIds: mock.no,fintlabs.no
    test-mode: true
    queue-endpoint-enabled: true

  audit:
    test-mode: true

  relations:
    force-https: false
    default-base-url: /

  hazelcast:
    members: localhost

server:
  context-path: ""
  port: 8080

endpoints:
  sensitive: false
  enabled: true

logging:
  level:
    no.fint.consumer.models.elev: DEBUG
