fint:
 events:
  orgIds: mock.no
  test-mode: true
  queue-endpoint-enabled: true

 audit:
  test-mode: true

 relations:
  force-https: false

 hazelcast:
  members: localhost

link-mapper-base-url: http://localhost:8080