springfox:
  title: '@title@'
  version: '@version@'

spring:
  mvc:
    logResolvedException: false

management:
  endpoint:
    prometheus:
      enabled: true
    shutdown:
      enabled: 'true'
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: 'full'
